var files_dup =
[
    [ "cmake-build-debug", "dir_95e29a8b8ee7c54052c171a88bb95675.html", "dir_95e29a8b8ee7c54052c171a88bb95675" ],
    [ "out", "dir_f09d564695a8a7f5713b0ef37bdf7d31.html", "dir_f09d564695a8a7f5713b0ef37bdf7d31" ],
    [ "BoardGame_Classes.h", "_board_game___classes_8h.html", "_board_game___classes_8h" ],
    [ "Connect4.cpp", "_connect4_8cpp.html", null ],
    [ "Connect4.h", "_connect4_8h.html", "_connect4_8h" ],
    [ "DiamondTicTacToe.cpp", "_diamond_tic_tac_toe_8cpp.html", null ],
    [ "DiamondTicTacToe.h", "_diamond_tic_tac_toe_8h.html", "_diamond_tic_tac_toe_8h" ],
    [ "FiveByFive.cpp", "_five_by_five_8cpp.html", null ],
    [ "FiveByFive.h", "_five_by_five_8h.html", "_five_by_five_8h" ],
    [ "fourxfourTicTacToe.cpp", "fourxfour_tic_tac_toe_8cpp.html", "fourxfour_tic_tac_toe_8cpp" ],
    [ "fourxfourTicTacToe.h", "fourxfour_tic_tac_toe_8h.html", "fourxfour_tic_tac_toe_8h" ],
    [ "Infinity_XO.cpp", "_infinity___x_o_8cpp.html", null ],
    [ "Infinity_XO.h", "_infinity___x_o_8h.html", "_infinity___x_o_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "Memory_XO.cpp", "_memory___x_o_8cpp.html", null ],
    [ "Memory_XO.h", "_memory___x_o_8h.html", "_memory___x_o_8h" ],
    [ "miser.cpp", "miser_8cpp.html", null ],
    [ "miser.h", "miser_8h.html", "miser_8h" ],
    [ "NUMERICALTICTACTOE.cpp", "_n_u_m_e_r_i_c_a_l_t_i_c_t_a_c_t_o_e_8cpp.html", null ],
    [ "NUMERICALTICTACTOE.h", "_n_u_m_e_r_i_c_a_l_t_i_c_t_a_c_t_o_e_8h.html", "_n_u_m_e_r_i_c_a_l_t_i_c_t_a_c_t_o_e_8h" ],
    [ "Obstacles_XO.cpp", "_obstacles___x_o_8cpp.html", null ],
    [ "Obstacles_XO.h", "_obstacles___x_o_8h.html", "_obstacles___x_o_8h" ],
    [ "pyramidTicTacToe.cpp", "pyramid_tic_tac_toe_8cpp.html", null ],
    [ "pyramidTicTacToe.h", "pyramid_tic_tac_toe_8h.html", "pyramid_tic_tac_toe_8h" ],
    [ "SUS.cpp", "_s_u_s_8cpp.html", null ],
    [ "SUS.h", "_s_u_s_8h.html", "_s_u_s_8h" ],
    [ "Ultimate_XO.cpp", "_ultimate___x_o_8cpp.html", null ],
    [ "Ultimate_XO.h", "_ultimate___x_o_8h.html", "_ultimate___x_o_8h" ],
    [ "Word_TicTacToe.cpp", "_word___tic_tac_toe_8cpp.html", "_word___tic_tac_toe_8cpp" ],
    [ "Word_TicTacToe.h", "_word___tic_tac_toe_8h.html", "_word___tic_tac_toe_8h" ],
    [ "XO_Board.h", "_x_o___board_8h.html", "_x_o___board_8h" ],
    [ "XO_Classes.cpp", "_x_o___classes_8cpp.html", null ],
    [ "XO_Classes.h", "_x_o___classes_8h.html", "_x_o___classes_8h" ],
    [ "XO_Demo.cpp", "_x_o___demo_8cpp.html", "_x_o___demo_8cpp" ]
];